# permissions for end users to view absurdcis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: absurdci-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: absurd-ci-operator-new
    app.kubernetes.io/part-of: absurd-ci-operator-new
    app.kubernetes.io/managed-by: kustomize
  name: absurdci-viewer-role
rules:
- apiGroups:
  - batch.api.absurd-ci.xyz
  resources:
  - absurdcis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.api.absurd-ci.xyz
  resources:
  - absurdcis/status
  verbs:
  - get
