---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch.api.absurd-ci.xyz
  resources:
  - absurdcis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.api.absurd-ci.xyz
  resources:
  - absurdcis/finalizers
  verbs:
  - update
- apiGroups:
  - batch.api.absurd-ci.xyz
  resources:
  - absurdcis/status
  verbs:
  - get
  - patch
  - update
