apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
      - name: my-container
        image: sujeshthekkepatt/absurd-ci-node-executor:v1.0.0
        command: ["/usr/local/bin/push-log.sh"]
        # Add any additional container configuration as needed
        imagePullPolicy: Always
  initContainers:
      - name: pi1
        image: sujeshthekkepatt/absurd-ci-node-executor:v1.0.0
        command: ["node", "--version"]
        imagePullPolicy: Always

      - name: pi2
        image: sujeshthekkepatt/absurd-ci-node-executor:v1.0.0
        command: ["npm", "--version"]
        imagePullPolicy: Always

      - name: pi3
        image: sujeshthekkepatt/absurd-ci-node-executor:v1.0.0
        command: ["node", "--help"]
        imagePullPolicy: Always

  restartPolicy: OnFailure
